--- #YAML:1.0
name: Class-Delegator
version: 0.02
author:
  - David Wheeler <david@kineticode.com>
abstract: Simple and fast object-oriented delegation
license: perl
build_requires:
  Test::Simple: 0.17
provides:
  Class::Delegator:
    file: lib/Class/Delegator.pm
    version: 0.02
generated_by: Module::Build version 0.26
