---
name: Class-Delegator
version: 0.06
author:
  - David Wheeler <david@kineticode.com>
abstract: Simple and fast object-oriented delegation
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Simple: 0.17
provides:
  Class::Delegator:
    file: lib/Class/Delegator.pm
    version: 0.06
generated_by: Module::Build version 0.2704
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
